<?php

# $Id$

// Written by James Flemer
// For eGrad2000.com
// <jflemer@acm.jhu.edu>
// <jflemer@eGrad2000.com>

?>
<div align="left"><pre><?php include($PIECES."/../../README"); ?></pre></div>
<p><a href="<?php echo($ME); ?>?where=manage">Go back to Management Interface</a></p>
<?php include($PIECES."/help".$EXT); ?>
<a href="<?php echo($ME); ?>?where=manage">Go back to Management Interface</a>
